config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path(settings.ADMIN_DOCS_URL, include('django.contrib.admindocs.urls')),

    # Authentication urls
    path('accounts/', include('django.contrib.auth.urls')),

    # Local apps
    path('catalog/', include('mylibrary.catalog.urls', namespace='catalog')),
]

# Add URL maps to redirect the base URL to our application
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mylibrary/catalog/urls.py
""" URLs for Catalog app """
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),

    # URLs for Books
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(),
         name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(),
         name='book_delete'),

    # URLs for Authors
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>',
         views.AuthorDetailView.as_view(), name='author_detail'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(),
         name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(),
         name='author_delete'),

    # URLs for Genres
    path('genres/', views.show_genres, name='genres'),
    path('genres/<slug:slug>', views.GenreDetail.as_view(),
         name='genre_detail'),
    path('genre/create/', views.GenreCreate.as_view(), name='genre_create'),
    path('genre/<int:pk>/update/', views.GenreUpdate.as_view(),
         name='genre_update'),
    path('genre/<int:pk>/delete/', views.GenreDelete.as_view(),
         name='genre_delete'),
]

mylibrary/catalog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from mptt.managers import TreeManager
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField


class Genre(MPTTModel):
    """ Model representing a book genre. """
    name = models.CharField(
        _('name'), max_length=200, unique=True,
        help_text=_('Enter a book genre (e.g. Science Fiction)'))
    slug = models.SlugField(
        _('slug'),
        # unique=True,
        max_length=255,
        help_text=_("Used to build the genre's URL."))
    definition = models.TextField(
        _('definition'), max_length=400, blank=True,
        help_text=_('Short description of the genre.'))
    parent = TreeForeignKey(
        'self', on_delete=models.CASCADE, null=True, blank=True,
        related_name='children', verbose_name=_('parent genre'),
        help_text=_('If this genre is a sub-genre, what does it belong to?')
        )

    objects = TreeManager()

    @property
    def tree_path(self):
        """
        Returns genre's tree path by concatening the slug of his ancestors.
        """
        if self.parent_id:
            return '/'.join(
                [ancestor.slug for ancestor in self.get_ancestors()] +
                [self.slug])
        return self.slug

    def get_absolute_url(self):
        """
        Builds and returns the genre's URL based on his tree path.
        """
        return reverse('catalog:genre_detail', args=(self.tree_path,))

    class MPTTMeta:
        """ Genre MPTT meta information. """
        order_insertion_by = ['name']

    class Meta:
        """ Genre meta information. """
        ordering = ['-name']

    def __str__(self):
        """String for representing the Genre object (in Admin site etc.)."""
        return self.name


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(_('first name'), max_length=100)
    middle_name = models.CharField(
        _('middle name'), max_length=50, blank=True)
    last_name = models.CharField(_('last name'), max_length=100)
    date_of_birth = models.DateField(_('born'), null=True, blank=True)
    date_of_death = models.DateField(_('died'), null=True, blank=True)
    bio = models.TextField(_('biography'), blank=True)
    pseudonyms = models.CharField(
        _('pseudonyms'), max_length=200, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('catalog:author_detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Author object."""
        return f'{self.last_name}, {self.first_name}'


class Book(models.Model):
    """ Model representing an instance of a Book. """

    class BookStatus(models.TextChoices):
        """ Choices for Book's status """
        WANT_TO_READ = 'WTR', _('Want to Read')
        CURRENTLY_READING = 'CR', _('Currently Reading')
        DID_NOT_FINISH = 'DNF', _('Did Not Finish')
        READ = 'R', _('Read')

    title = models.CharField(_('title'), max_length=200)
    author = models.ForeignKey(
        Author, null=True,
        on_delete=models.SET_NULL)
    status = models.CharField(
        _('status'), max_length=3,
        choices=BookStatus.choices,
        default=BookStatus.WANT_TO_READ)
    overall_rating = models.PositiveSmallIntegerField(
        _('overall rating'), default=0)
    # Book Details
    summary = models.TextField(
        _('summary'), max_length=1000,
        help_text=_('Enter a brief description of the book (max char=1000).'))
    isbn = models.CharField(
        _('ISBN'), max_length=13, blank=True,
        help_text=_('13 Character ISBN number')
        )
    genre = TreeManyToManyField(
        Genre, blank=True, related_name='books',
        help_text=_('Select a genre for this book.'))
    pages = models.PositiveSmallIntegerField(
        _('pages'), null=True, help_text=_('Number of pages.'))
    # Dates
    date_added = models.DateTimeField(
        _('added'), default=timezone.now)
    date_read = models.DateField(
        _('date read'), null=True, blank=True,
        help_text=_('Enter the date when read.'))
    date_published = models.DateField(
        _('date published'), null=True, blank=True,
        help_text=_('Enter the date of publication.'))

    objects = models.Manager()

    class Meta:
        ordering = ['-date_added', ]
        indexes = [models.Index(fields=['author', 'title']), ]

    def __str__(self):
        """ String for representing the Book object. """
        return self.title

    def get_absolute_url(self):
        """ Returns the url to access a detail record for this book. """
        return reverse("catalog:book_detail", kwargs={"pk": self.pk})

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to
        display genre in Admin.
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    # def save(self, *args, **kwargs):
    #     """ Update fields with calculations upon saving """

        # def calculate_rating(self):
        #     """ Populates overall_rating field with calculated rating """
        #     overall = Rating.objects.filter(book=self).aggregate(
        #         models.Avg('rating'))
        #     return overall
        # self.overall_rating = calculate_rating

        # def get_rating(self):
        #     """ Populates overall_rating field with calculated rating """
        #     overall = Rating.objects.filter(book=self).annotate(
        #         avg=models.Avg('book__ratings'))
        #     return overall
        # self.overall_rating = get_rating

    #    super(Book, self).save(*args, **kwargs)


class RatingType(models.Model):
    """ Model representing the various rating types. """
    name = models.CharField(
        _('type'), max_length=50,
        help_text=_('Type of rating.'))
    slug = models.SlugField(
        _('slug'), max_length=60, unique=True)
    description = models.TextField(
        _('description'),
        help_text=_('Description of the rating type.'))

    class Meta:
        verbose_name = _("Rating Type")
        verbose_name_plural = _("Rating Types")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("RatingType_detail", kwargs={"pk": self.pk})


class Rating(models.Model):
    """ Model representing the actual rating assigned to a book. """

    class RateChoices(models.IntegerChoices):
        """ Choices for the Rating fields """
        LOWEST = 1, _('1 Star')
        LOW = 2, _('2 Stars')
        OK = 3, _('3 Stars')
        HIGH = 4, _('4 Stars')
        HIGHEST = 5, _('5 Stars')

        __empty__ = _('None')

    book = models.ForeignKey(
        Book, related_name='ratings', on_delete=models.CASCADE)
    rating_type = models.ForeignKey(
        RatingType, related_name='ratings', on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        _('rating'), choices=RateChoices.choices,
        help_text=_('Rate where 1 is low and 5 is high'))
    comments = models.TextField(
        _('comments'), max_length=500, blank=True,
        help_text=_('Comments supporting this rating.'))

    class Meta:
        verbose_name = _("Rating")
        verbose_name_plural = _("Ratings")

    def __str__(self):
        return '{0} - {1}'.format(self.book.title, self.rating_type.name)

    def get_absolute_url(self):
        return reverse("Rating_detail", kwargs={"pk": self.pk})

mylibrary/catalog/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Book, Author, Genre


def index(request):
    """ View function for home page of site. """

    # Generate counts of some of the main objects
    num_books = Book.objects.count()
    num_authors = Author.objects.count()
    num_genres = Genre.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'catalog/index.html', context=context)


# Book views
class BookListView(ListView):
    """ View for List of Books """
    model = Book
    paginate_by = 20


class BookDetailView(DetailView):
    model = Book


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_add_books'


class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_change_books'


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'catalog.can_delete_books'


# Author views
class AuthorListView(ListView):
    """Generic class-based list view for a list of authors."""
    model = Author
    paginate_by = 20


class AuthorDetailView(DetailView):
    """Generic class-based detail view for an author."""
    model = Author


class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'
    # initial = {'date_of_death': '05/01/2018'}
    permission_required = 'catalog.can_add_authors'


class AuthorUpdate(UpdateView):
    model = Author
    fields = [
        'first_name', 'last_name', 'pseudonyms', 'bio',
        'date_of_birth', 'date_of_death'
    ]
    permission_required = 'catalog.can_change_authors'


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.can_delete_authors'


# Genre views
def show_genres(request):
    """ View function for a list of Genres """
    return render(
        request, "catalog/genres.html", {'genres': Genre.objects.all()})


class GenreDetail(DetailView):
    """ Genre detail view """
    model = Genre
    template_name = 'catalog/genre_detail.html'


class GenreCreate(PermissionRequiredMixin, CreateView):
    model = Genre
    fields = '__all__'
    permission_required = 'catalog.can_add_genres'


class GenreUpdate(PermissionRequiredMixin, UpdateView):
    model = Genre
    fields = '__all__'
    permission_required = 'catalog.can_change_genres'


class GenreDelete(PermissionRequiredMixin, DeleteView):
    model = Genre
    success_url = reverse_lazy('genres')
    permission_required = 'catalog.can_delete_genres'

mylibrary/templates/catalog/author_confirm_delete.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}

{% blocktrans %}
  <h1>Delete Author</h1>
  <p>Are you sure you want to delete the author: 
{% endblocktrans %}
  <strong>{{ author }}</strong>?
  </p>

  <form action="" method="POST">
    {% csrf_token %}
    <input class="ui red button" type="submit" value="Yes, delete.">
    <a class="ui button" href="javascript:history.go(-1)">
      {% trans 'Cancel' %} </a>
  </form>

{% endblock page-content %}

mylibrary/templates/catalog/author_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}
<div class="ten wide column">

  <h1 class="page-title">{% trans 'Author: ' %}<span>{{ author }}</span></h1>
  <small>
  {% if author.date_of_birth %}
    <p>{{author.date_of_birth}} - 
      {% if author.date_of_death %}{{author.date_of_death}}{% endif %}
    </p>
  {% endif %}
  </small>
  <p>{{ author.bio|linebreaks }}</p>

  <a class="ui mini button btn" href="{% url 'catalog:author_update' author.pk %}">
        {% trans 'Edit Author' %} </a>
  <a class="ui red mini button" href="{% url 'catalog:author_delete' author.pk %}">
        {% trans 'Delete Author' %} </a>  
  <hr>

  <div style="margin-left:20px;margin-top:20px">
  <h3>{% trans 'Books' %}</h3>

  {% for book in author.book_set.all %}
  <div class="ui fluid segment">
    <h4>
      <a href="{% url 'catalog:book_detail' book.pk %}">{{book}}</a>
      <small>({{ book.date_published|date:"Y" }})</small>
    </h4>
    <dd>{{book.summary|linebreaks}}</dd>
  </div>
  {% endfor %}
  </div>

</div>
{% endblock page-content %}

mylibrary/templates/catalog/author_form.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}
<div class="sixteen wide column">

  <h1>{% trans 'Author Create / Update' %}</h1>
  <form class="ui form" action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input class="ui button btn" type="submit" value="Submit">
    <a class="ui button" href="javascript:history.go(-1)">
      {% trans 'Cancel' %} </a>
  </form>

</div>
{% endblock page-content %}

mylibrary/templates/catalog/author_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}
<div class="sixteen wide column">

  <h1>{% trans 'Author List' %}</h1>
  <a class="ui mini button btn" href="{% url 'catalog:author_create' %}">
        {% trans 'Add New Author' %} </a>
  <hr>

  {% if author_list %}
    <ul>
      {% for author in author_list %}
        <li>
          <a href="{{ author.get_absolute_url }}">
          {{ author }} 
          {% if author.date_of_birth %}
            ({{author.date_of_birth}} - 
              {% if author.date_of_death %}{{author.date_of_death}}{% endif %})
          </a>
        </li>
          {% endif %}
          
      {% endfor %}
    </ul>

  {% else %}
    {% blocktrans %}
      <p>There are no authors available.</p>
    {% endblocktrans %}

  {% endif %}

</div>
{% endblock page-content %}

mylibrary/templates/catalog/book_confirm_delete.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}

{% blocktrans %}
  <h1>Delete Book</h1>
  <p>Are you sure you want to delete the book: 
{% endblocktrans %}
  <strong>{{ book }}</strong>?
  </p>

  <form action="" method="POST">
    {% csrf_token %}
    <input class="ui red button" type="submit" value="Yes, delete.">
    <a class="ui button" href="javascript:history.go(-1)">
      {% trans 'Cancel' %} </a>
  </form>

{% endblock page-content %}

mylibrary/templates/catalog/book_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}
<div class="sixteen wide column">

  <h1>{% trans 'Title: ' %}{{ book.title }}</h1>

  <a class="ui teal mini button" href="{% url 'catalog:book_update' book.pk %}">
      {% trans 'Edit Book' %} </a>
  <a class="ui red mini button" href="{% url 'catalog:book_delete' book.pk %}">
      {% trans 'Delete Book' %} </a>

  <p><strong>{% trans 'Author: ' %}</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>{% trans 'Summary: ' %}</strong> {{ book.summary|linebreaks }}</p>
  <p><strong>{% trans 'ISBN: ' %}</strong> {{ book.isbn }}</p> 
  <p><strong>{% trans 'Published: ' %}</strong> {{ book.date_published|date:"F j, Y" }}</p> 
  <p><strong>{% trans 'Genre: ' %}</strong> {{ book.display_genre }}</p>

</div>
{% endblock page-content %}

mylibrary/templates/catalog/book_form.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}
<div class="sixteen wide column">

  <h1>{% trans 'Book Create/Update' %}</h1>
  <form class="ui form" action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input class="ui button btn" type="submit" value="Submit">
    <a class="ui button" href="javascript:history.go(-1)">
      {% trans 'Cancel' %} </a>
  </form>

</div>
{% endblock page-content %}

mylibrary/templates/catalog/book_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}
<div class="sixteen wide column">

  <h1>{% trans 'Book List' %}</h1>
  <a class="ui mini button btn" href="{% url 'catalog:book_create' %}">
      {% trans 'Add New Book' %} </a>
  <hr>

  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> 
        ({{book.author}})
        <small>{{ book.display_genre }}</small>
        
      </li>
    {% endfor %}
  </ul>
  {% else %}
    {% blocktrans %}
    <p>There are no books in the library.</p>
    {% endblocktrans %}
  {% endif %} 

</div>
{% endblock page-content %}

mylibrary/templates/catalog/genre_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}
<div class="sixteen wide column">

  <h1 class="page-title">{% trans 'Title: ' %}<span>{{ genre.name }}</span></h1>

  <!-- {% comment %}
    <a class="ui teal mini button" href="{% url 'catalog:genre_update' genre.pk %}">
      {% trans 'Edit Genre' %} </a>
  <a class="ui red mini button" href="{% url 'catalog:genre_delete' genre.pk %}">
      {% trans 'Delete Genre' %} </a> 
    {% endcomment %} -->

  <p><strong>{% trans 'Definition: ' %}</strong> {{ genre.definition|linebreaks }}</p>
  <p><strong>{% trans 'Parent: ' %}</strong> {{ genre.parent }}</p> 


</div>
{% endblock page-content %}

mylibrary/templates/catalog/genre_form.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}
<div class="sixteen wide column">

  <h1>{% trans 'Genre Create/Update' %}</h1>
  <form class="ui form" action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input class="ui button btn" type="submit" value="Submit">
    <a class="ui button" href="javascript:history.go(-1)">
      {% trans 'Cancel' %} </a>
  </form>

</div>
{% endblock page-content %}

mylibrary/templates/catalog/genres.html
{% extends "base.html" %}
{% load static i18n %}
{% load mptt_tags %}

{% block page-content %}
<div class="sixteen wide column">

  <h1>{% trans 'List of Genres' %}</h1>
  <a class="ui mini button btn" href="{% url 'catalog:genre_create' %}">
    {% trans 'Add New Genre' %} </a>
  <hr>

  <ul>
    {% recursetree genres %}
    <li>
      {{ node.name }}
      {% if not node.is_leaf_node %}
      <ul class="children">
        {{ children }}
      </ul>
      {% endif %}
    </li>
    {% endrecursetree %}
  </ul>

</div>
{% endblock page-content %}

mylibrary/templates/catalog/index.html
{% extends "base.html" %}
{% load static i18n %}

{% block page-content %}
<div class="sixteen wide column">
  {% blocktrans %}
    <h1 class="lib-brand__dark"><span>my</span>Library Home</h1>
    <p>Welcome to <strong class="lib-brand__dark"><span>my</span>Library</strong>, 
        a website developed by <em>Mozilla Developer Network</em>!</p>
  {% endblocktrans %}

  <div class="ui inverted segment">
    <h2>Dynamic content</h2>
    <p>The library has the following record counts:</p>

    <ul>
      <li>
        <strong><a class="item" href="{% url 'catalog:books' %}">
          {% trans 'Books: ' %}</a></strong> {{ num_books }}
      </li>
      <li>
        <strong><a class="item" href="{% url 'catalog:authors' %}">
          {% trans 'Authors: ' %}</a></strong> {{ num_authors }}
      </li>
      <li>
        <strong><a class="item" href="{% url 'catalog:genres' %}">
          {% trans 'Genres: ' %}</a></strong> {{ num_genres }}
      </li>
    </ul>
  
  </div>

  <p><em>{% trans 'You have visited this page ' %} {{ num_visits }}
    {% if num_visits == 1 %}{% trans 'time' %}
    {% else %}{% trans 'times' %}
    {% endif %}.</em></p>
</div>
{% endblock page-content %}